services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Pforum\:
    resource: '../Classes/*'

  JWeiland\Pforum\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Pforum\Event\PostProcessFluidVariablesEvent
